From joshelser/sqlline

ADD https://repo1.maven.org/maven2/org/apache/phoenix/phoenix-queryserver-client/4.9.0-HBase-1.2/phoenix-queryserver-client-4.9.0-HBase-1.2.jar /sqlline/lib

ENTRYPOINT ["/sqlline/sqlline.py", "--classpath", "/sqlline/lib/*"]
